'''
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

'''

#Solutions:

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        #solution 1: Using ord and chr with O(n) time and O(1) space

        '''
        
        s_sum, t_sum = 0, 0
        for char in s:
            s_sum += ord(char)
        for char in t:
            t_sum += ord(char)
        
        return chr(t_sum - s_sum)
        
        '''

        #solution 2: Using hash map with O(n) time and O(26) which is equal to O(1) constant space

        '''


        charHash = {}
        for x in s:
            if x in charHash:
                charHash[x] += 1
            else:
                charHash[x] = 1
        
        for y in t:
            if y not in charHash or charHash[y] == 0:
                return y
            else:
                charHash[y] -= 1
            

        '''

        #Solution 3: Using bit manipulation, time complexity- O(n) and space is O(1), here we are just XORing all the characters of both the strings to find the odd duckling.

        resultingXor = 0
        for i in range(len(s)):
            resultingXor ^= ord(s[i]) ^ ord(t[i])
        
        resultingXor ^= ord(t[-1])
        return chr(resultingXor)



